### PR TITLE
Awesome books: style core elements

### PR DESCRIPTION
**Pull request by popoolahussein**
# Description:
[wireframe]: https://github.com/adejam/javascript-curriculum/blob/main/books/images/awesome_books_core_elements.png
[linter]: https://github.com/popoolahussein/Awesome-books/pull/4/checks
### General Requirements:
   * Ensured there are no [linter][linter] errors.
   * Followed the correct GitHub flow.
   * Documented work in a professional manner.
   * Adhered to the best practices for HTML & CSS.
   * Added CSS styles to the application to match the provided wireframe.
   * Used plain CSS to style the application.
### Project Requirements
   * Implemented CSS styles to align the application with the overall layout specified in the provided wireframe.
  * Emphasized the overall layout rather than focusing on minor details.
  * Incorporated custom colors, fonts, backgrounds, and other stylistic elements to improve the user interface.
### Changes Made:
  * Header Styling:
    * Improved the appearance of the header to ensure it aligns with the wireframe.
    * Adjusted font size, color, and margin for better visual hierarchy.
  * Book List Styling:
    * Styled the book list section to match the wireframe.
    * Used alternating background colors for book items to enhance readability.
    * Added border and padding to book items for a cleaner look.
  * Form Styling:
    * Styled the form to align with the wireframe.
    * Adjusted input fields and buttons for better alignment and usability.
    * Ensured the add button is positioned correctly at the right side of the form.

### General Layout
  * Ensured the overall layout of the application matches the wireframe.
  * Concentrated on maintaining a consistent look and feel across the application.

### Preview:
  * How to Test:
    * Clone the repository and navigate to the project directory.
    * Open the index.html file in a browser.
    * Verify that the application UI matches the wireframe.
    * Ensure all functionalities (adding, displaying, and removing books) are working as expected.

  * Screenshot of the completed work:

Screenshot (412)

##### Conclusion:
* This pull request enhances the Awesome Books application by adding CSS styles that improve its visual appeal and align it with the provided wireframe. All changes adhere to the project's requirements and best practices for HTML & CSS.

### CODE REVIEW

**Review by adejam — CHANGES_REQUESTED** [review]
The design looks good to me. However, when testing, I noticed that the books are being deleted by book title... This is not the ideal, we can go for two other options

1. Ensure two title is unique per book. This way no two books can have the same title.
2. Which I recommend the most is that each book will have it's own uniquely generated id when added, this way the Id can be used to delete the book, or even update it incase you ever plan to add update feature.

Please look into this.

**Review by landpeacelogistics — CHANGES_REQUESTED** [review]
## Looks Good. Has little issue

There is a little issue, I'll list the reproduction step..

1. add a book with title "fff",
2. Try to add another book with title "fff" - You get an alert that "A book with this title already exists." which implies the system doesn't allow adding two books with same title.
3. Delete the current book with title "fff". The books moves to trash.
4. Add another book with title "fff". the book gets added.
5. restore the previous deleted book with title "fff"... The book gets restored which means we now have two books with the same title...

This is confusing as it conflicts with the alert of not having books witht the same title... 
What is the decision here:
1. Do we want to have two books with same title?. This case the alert is not needed.
2. Do we want to restrict having two books with same title, in this case when a user wants to restore the book then they shouldn't be able to or it should get deleted automatically...

PLease make a decision here

**Comment by popoolahussein** [comment]
@landpeacelogistics 
## This comment is appreciated. 
* Our goal is to restrict having two books with the same title, the functionality was omitted due to inadequate inspection, this comment will be attended to as soon as possible.

**Comment by popoolahussein** [comment]
@adejam 
@landpeacelogistics
>
### All previously received comments have been a positive contribution. Based on the comments received, we have been able to achieve the goal of building a bookstore with unique functionalities.
>
### Changes Made:
  * Duplicate Book Title Check:
      * Added a mechanism to prevent adding duplicate book titles.
     *  When a user attempts to add a book with a title that already exists, a modal dialog is displayed with the message "A book with this title already exists."

  * Book Removal and Restoration Logic:
      * Updated the removeBook method to move the book to a removed books list.
      * Implemented the restoreBook method to allow users to restore previously removed books.
     *  Ensured that restoring a book checks for duplicate titles to maintain the integrity of the title uniqueness constraint.
  * Modular Modal Dialog Handling:
      * Created a showModal function to display messages in a modal dialog for better user interaction.
      * Introduced a showEditModal function to handle editing book details within a modal dialog.

  * Local Storage Management:
      * Enhanced local storage handling to store and retrieve both active and removed books.
      * Updated the updateLocalStorage method to handle both active and removed books, ensuring persistence across sessions.

  * UI Updates:
      * Updated the createBookElement and createRemovedBookElement methods to include buttons for removing, restoring, and editing books.
      * Improved the display logic in displayBooks to reflect the current state of the active and removed books.

  * Event Handling Improvements:
      * Streamlined event handling for form submission, book removal, restoration, and editing.
      * Ensured modals close properly on clicking outside or using the close button.

### Testing:

- [x] Tested the application on multiple devices to ensure responsiveness and proper functionality of the added features.
- [x] Verified that duplicate titles are not allowed in both active and removed book lists.
- [x] Confirmed that modals display appropriate messages and close correctly.

#### screenshot of the job done:

Screenshot (421)

**Review by adejam — APPROVED** [review]
# LGTM

Looks good to me... Please merge... Goodluck on your next milestones

**Comment by popoolahussein** [comment]
> # LGTM
> Looks good to me... Please merge... Goodluck on your next milestones

## All comments are sincerely appreciated.

**Pull request merged**
